
// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using ToGrayscaleConverter;


namespace TrainedModel
{
    public class Program
    {
        static void Main(string[] args)
        {
            using (StreamWriter outputFileTest = new StreamWriter("C:/Users/artem/Desktop/AI/PreProcess/testOutput.txt"))
            {
                string value2 = ToGrayscaleConverter.ExtractorProgram.ExtractProperties("C:/Users/artem/Desktop/AI/PreProcess/test.jpg", outputFileTest, "4");
                Predict(value2);
            }
        }


        public static void Predict(string vector)
        {
            MLModel.ModelInput model = new MLModel.ModelInput();
            PropertyInfo[] properties = model.GetType().GetProperties();

            List<int> values = vector.Split(',').Select(int.Parse).ToList();

            //Lists all prediction
            int counter = 0;
            int x = values.Count;


            foreach (var property in properties)
            {
                if (property.Name == "Col0") continue;
                property.SetValue(model, values[counter++]);
            }


            // Make a single prediction on the sample data and print results
            var predictionResult = MLModel.Predict(model);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Col0 with predicted Col0 from sample data...\n\n");


            Console.WriteLine($"\n\nPredicted Col0: {predictionResult.Prediction}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
